spring:
  application:
    name: company-service

  datasource:
    url: jdbc:postgresql://localhost:5432/test_database
    username: test_user
    password: test_password

  jpa:
    hibernate:
#      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  microservice:
    location:
      base-url: http://localhost:9001/locations/

server:
  port: 9002

