spring:
  application:
    name: COMPANY-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/test_database
    username: test_user
    password: test_password

  jpa:
    hibernate:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  microservice:
    location:
      base-url: http://LOCATION-SERVICE/locations/

server:
  port: 9002

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

