spring:
  application:
    name: user-service
  data:
    mongodb:
      authentication-database: admin
      username: test_user
      password: test_password
      database: user_mongodb
      port: 27017
      host: localhost

server:
  port: 9003

microservice:
  routes:
    location:
      className: LocationDto
      baseUrl: http://localhost:9001/locations/
    company:
      className: CompanyDto
      baseUrl: http://localhost:9002/companies/

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED